### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by ruscourier** [steinarb/opds-reader#11]
Hi,

Can't install plugin, because:

(base) ➜  calibre_plugin git:(master) calibre-customize -b .
zsh: command not found: calibre-customize

![cip](https://user-images.githubusercontent.com/61388836/94995695-aa048680-05a8-11eb-860e-3621b7372c62.png)

**Comment by steinarb** [comment]
What version of calibre on what OS?

**Comment by ruscourier** [comment]
5.1 on Mac

**Comment by steinarb** [comment]
Then you'll need to figure out where calibre is installed and add the directory containing the binaries to the PATH environment variable.

Alternatively you can run calibre-customize with the full path to the command.

I don't have access to a mac, so I can't help you any more than this, sorry.

**Comment by ruscourier** [comment]
I did it, it looks like:

(base) ➜  macos /Applications/calibre.app/Contents/MacOS/calibre-customize -b /Users/<user folder>/opds-reader/calibre_plugin
Plugin updated: OPDS Client (1, 0, 0)
(base) ➜  macos

10xs for help
