### ISSUE TITLE
Select book format to download from OPDS feed

### ISSUE THREAD

**Issue by PiperKev** [steinarb/opds-reader#29]
I don't know if this is possible or not, but is there any way to select the format of the book that can be downloaded from the OPDS feed?  For example, I use the OPDS client to check for revisions to ebooks from Standard Ebooks (https://standardebooks.org/opds).  When I select a book to download, it automatically downloads the epub format, which I really can't use since I have a kindle (I know, I can convert with calibre, but I'd rather have it in the azw3 format that SE provides).

**Comment by PiperKev** [comment]
Any updates to this?  Is it possible?

**Comment by steinarb** [comment]
I have no plans to do it.

But I will take and include a PR if it isn't too intrusive (i.e. keep the current behaviour as default, and make it possible to configure the behaviour you want or something).

Being prompted every time for whether to download the epub or azw3, counts as "too intrusive".

**Comment by PiperKev** [comment]
Fair enough.  Someone on the Standard Ebooks mailing list showed me a fix that works perfectly:

"On lines 171-173 of https://github.com/steinarb/opds-reader/blob/master/calibre_plugin/model.py you'll see that .epub formats are explicitly selected by the plugin. Change these lines:

    if bookType == 'application/epub+zip':
        # EPUB books are preferred and always put at the head of the list if found
        bookDownloadUrls.insert(0, url)

to your preferred SE publication format:

application/epub+zip
application/kepub+zip
application/x-mobipocket-ebook (this one is azw3)"

**Comment by steinarb** [comment]
(FWIW Making the preferred content type configurable counts as "non-intrusive" in my book)
