### ISSUE TITLE
OPDS Client fails with calibre 5.38.0

### ISSUE THREAD

**Issue by PiperKev** [steinarb/opds-reader#31]
This morning I upgraded calibre to the latest version, 5.38.0.  After restarting, I attempted to invoke the OPDS Client plugin, and it failed with a "KeyError: 'Server'" error.  I restarted calibre in debug mode and produced the following log file:

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 5.38  embedded-python: True is64bit: True
Linux-5.13.0-28-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.13.0-28-generic', '#31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 47, 0) && Find Duplicates (1, 9, 4) && Goodreads (1, 5, 3) && Goodreads Sync (1, 15, 1) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Kindle hi-res covers (0, 5, 0) && OPDS Client (1, 0, 0) && Obok DeDRM (7, 2, 1) && Search The Internet (1, 8, 1) && Standard Ebooks (1, 0, 0)
calibre 5.38  embedded-python: True is64bit: True
Linux-5.13.0-28-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.13.0-28-generic', '#31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 47, 0) && Find Duplicates (1, 9, 4) && Goodreads (1, 5, 3) && Goodreads Sync (1, 15, 1) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Kindle hi-res covers (0, 5, 0) && OPDS Client (1, 0, 0) && Obok DeDRM (7, 2, 1) && Search The Internet (1, 8, 1) && Standard Ebooks (1, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.99999999999999 x 128.18691588785046
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.6 HttpHelper::__init__: proxy=None
[0.93] main UI initialized...
[0.93] Hiding splash screen
Starting QuickView
Failed to initialize plugin: '/home/kevin/.config/calibre/plugins/Inept Epub DeDRM.zip'
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 740, in initialize_plugins
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 292, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 184, in exec_module
  File "calibre/customize/zipplugin.py", line 180, in get_code
  File "calibre_plugins.ineptepub.__init__", line 168
    print 'IneptEpub: Using libcrypto.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('IneptEpub: Using libcrypto.')?
calibre 5.38  embedded-python: True is64bit: True
Linux-5.13.0-28-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.13.0-28-generic', '#31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 47, 0) && Find Duplicates (1, 9, 4) && Goodreads (1, 5, 3) && Goodreads Sync (1, 15, 1) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Kindle hi-res covers (0, 5, 0) && OPDS Client (1, 0, 0) && Obok DeDRM (7, 2, 1) && Search The Internet (1, 8, 1) && Standard Ebooks (1, 0, 0)
Traceback (most recent call last):
  File "calibre_plugins.opds_client.ui", line 24, in show_dialog
    d = OpdsDialog(self.gui, self.qaction.icon(), do_user_config)
  File "calibre_plugins.opds_client.main", line 68, in __init__
    catalogsTuple = self.model.downloadOpdsRootCatalog(self.gui, self.opdsUrlEditor.currentText(), False)
  File "calibre_plugins.opds_client.model", line 78, in downloadOpdsRootCatalog
    self.serverHeader = feed.headers['Server']
KeyError: 'Server'

[3.39] splash screen hidden
[3.39] Started up in 3.39 seconds with 642 books**

After reinstalling calibre 5.37.0, the plugin worked as normal.

**Comment by PiperKev** [comment]
Additional info from Kovid Goyal, the author of calibre:

"That will be be because feedparser bundled with calibre is updated to version 6. If the plugin needs version 5 it should use its own private copy."

**Comment by steinarb** [comment]
Started calibre 5.36 on windows 10, and verified that the plugin worked there.

Downloaded and installed calibre 5.38.

Got an error in calibre 5.38
```
calibre, version 5.38.0
ERROR: Unhandled exception: <b>KeyError</b>:'Server'

calibre 5.38 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: OPDS Client (1, 0, 0)
Traceback (most recent call last):
  File "calibre_plugins.opds_client.ui", line 24, in show_dialog
  File "calibre_plugins.opds_client.main", line 68, in __init__
  File "calibre_plugins.opds_client.model", line 78, in downloadOpdsRootCatalog
KeyError: 'Server'
```

@PiperKev I'll look into the feedparser version issue, thanks for the heads up!

**Comment by steinarb** [comment]
@PiperKev I have pushed a fix, please test!

**Comment by PiperKev** [comment]
Will do!  I'm away from home currently,  but I'll test it as soon as I get
back home tonight!

Thanks!
Kevin

**Comment by PiperKev** [comment]
I verified that it works with calibre 5.38!  thanks so much for the quick fix, @steinarb !!
