### ISSUE TITLE
[Feature Request] Download All Button

### ISSUE THREAD

**Issue by OdinVex** [steinarb/opds-reader#35]
A 'Download All' button might be nice to have (allowing for hiding any books in user library already).

Edit: A button to 'select all' might be better, it'd allow for more fine-grain control in the end.
Edit: For now, I've set the `SelectionMode` to `QAbstractItemView::ExtendedSelection` which allows cursor drag-selection.

**Comment by steinarb** [comment]
Not something I need, but I'll take a PR if the button doesn't look awful when I open the download dialog.
