### ISSUE TITLE
Does this work with Calibre 3.x?

### ISSUE THREAD

**Issue by Geremia** [steinarb/opds-reader#4]
Does this work with Calibre 3.x?
I tried it, and it ran into an error.

**Comment by steinarb** [comment]
I'm running the opds-reader with calibre 3.19 on windows 10 and on debian 9.4 "stretch".

What is the error message you're getting? What OS are you runnng on? How did you install calibre on that system? How did you go about to install opds-reader?

**Comment by steinarb** [comment]
As of today, the master HEAD of this plugin will only run on calibre 5 and later.
